import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { SocketProvider } from "@/context/SocketProvider";
import { Suspense } from "react";
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] });
const mostserrat = Montserrat({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <body className={cn(mostserrat.className)}>
          <main className="bg-slate-950 min-h-screen">
            <Suspense>
              <SocketProvider>
                {children}
              </SocketProvider>
            </Suspense>
          </main>
        </body>
      </html>
    // </ClerkProvider>
  );
}
